//=============================================================================
// dog_fir_single.v
//
// Single-channel DoG (Difference-of-Gaussians) multi-scale temporal filter.
// This is the CORE DSP block of the TTCGS pipeline. One channel only; the
// full design instantiates / time-multiplexes this across 19 channels later.
//
// WHAT IT DOES (matches the Python golden model):
//   - keeps the last 256 input samples in a circular buffer
//   - convolves them with three causal Gaussian kernels (sigma = 2, 8, 85)
//     using ONE multiply-accumulate engine, time-multiplexed across scales
//   - outputs G_s1, G_s2, G_s3 (smoothed) and
//     DoG_fast = G_s1 - G_s2,  DoG_slow = G_s2 - G_s3
//
// FIXED-POINT (from fixed_point_analysis.py):
//   - input        : signed 16-bit
//   - coefficients : Q15 (1.0 = 32768), stored in ROM, 3 x 256 = 768 entries
//   - accumulator  : 39-bit signed (prevents overflow over 256 taps)
//   - output       : signed 16-bit after >>15 (undo Q15 scaling)
//   Verified DoG SNR vs float: ~53 dB (fast), ~63 dB (slow).
//
// HANDSHAKE:
//   - assert `sample_valid` for 1 clk with a new `sample_in`
//   - the engine runs through all 3 scales (time-multiplexed MAC)
//   - when done, `result_valid` pulses and G_s1/2/3 + DoG outputs are stable
//
// Target: Tang Nano 9K (GW1NR-LV9), uses 1 DSP (the MAC multiplier).
//=============================================================================

module dog_fir_single #(
    parameter N_TAPS    = 256,
    parameter ADDR_BITS = 8,    // log2(256)
    parameter FRAC      = 15    // Q15
)(
    input  wire                 clk,
    input  wire                 rst_n,

    input  wire signed [15:0]   sample_in,     // new input sample
    input  wire                 sample_valid,  // 1-clk pulse: new sample ready

    output reg  signed [15:0]   G_s1,          // smoothed, sigma=2
    output reg  signed [15:0]   G_s2,          // smoothed, sigma=8
    output reg  signed [15:0]   G_s3,          // smoothed, sigma=85
    output reg  signed [15:0]   DoG_fast,      // G_s1 - G_s2
    output reg  signed [15:0]   DoG_slow,      // G_s2 - G_s3
    output reg                  result_valid   // 1-clk pulse when outputs ready
);

    //=========================================================================
    // COEFFICIENT ROM (Q15)
    // Layout: [sigma2: 0..255][sigma8: 256..511][sigma85: 512..767]
    // Loaded from dog_coeffs.mem (generated by gen_coeffs.py).
    //=========================================================================
    reg signed [15:0] coef_rom [0:3*N_TAPS-1];
    initial $readmemh("dog_coeffs.mem", coef_rom);

    //=========================================================================
    // CIRCULAR SAMPLE BUFFER
    // Stores the last 256 samples. `head` points to the newest sample.
    // For tap k, we read buffer[head - k] (wrapping).
    //=========================================================================
    reg signed [15:0] sbuf [0:N_TAPS-1];
    reg [ADDR_BITS-1:0] head;       // index of newest sample

    //=========================================================================
    // MAC ENGINE (time-multiplexed across 3 scales)
    //=========================================================================
    localparam IDLE = 2'd0, RUN = 2'd1, DONE = 2'd2;
    reg [1:0]  state;
    reg [1:0]  scale;               // 0=sigma2, 1=sigma8, 2=sigma85
    reg [ADDR_BITS-1:0] tap;        // current tap index 0..255
    reg signed [38:0] acc;          // 39-bit accumulator
    reg signed [15:0] g_result [0:2]; // holds G_s1/2/3 during compute

    // address helpers
    wire [ADDR_BITS-1:0] buf_idx  = head - tap;          // wraps automatically
    wire [9:0]           coef_idx = {scale, 8'd0} + tap; // scale*256 + tap
    wire signed [15:0]   x_tap    = sbuf[buf_idx];
    wire signed [15:0]   c_tap    = coef_rom[coef_idx];
    wire signed [31:0]   product  = x_tap * c_tap;       // 16x16 -> 32-bit

    integer i;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state        <= IDLE;
            head         <= {ADDR_BITS{1'b0}};
            scale        <= 2'd0;
            tap          <= {ADDR_BITS{1'b0}};
            acc          <= 39'sd0;
            result_valid <= 1'b0;
            G_s1 <= 16'sd0; G_s2 <= 16'sd0; G_s3 <= 16'sd0;
            DoG_fast <= 16'sd0; DoG_slow <= 16'sd0;
            for (i=0; i<N_TAPS; i=i+1) sbuf[i] <= 16'sd0;
        end else begin
            result_valid <= 1'b0;   // default: no pulse

            case (state)
            //-----------------------------------------------------------------
            IDLE: begin
                if (sample_valid) begin
                    // store new sample at the next head position
                    head        <= head + 1'b1;
                    sbuf[head + 1'b1] <= sample_in;
                    // begin MAC over scale 0, tap 0
                    scale <= 2'd0;
                    tap   <= {ADDR_BITS{1'b0}};
                    acc   <= 39'sd0;
                    state <= RUN;
                end
            end
            //-----------------------------------------------------------------
            RUN: begin
                // accumulate product for current (scale, tap)
                acc <= acc + {{7{product[31]}}, product};   // sign-extend to 39-bit

                if (tap == N_TAPS-1) begin
                    // finished all taps for this scale: store G_result
                    // (acc holds sum of x*coef in Q15; >>15 to get back to int)
                    g_result[scale] <= (acc + {{7{product[31]}}, product}) >>> FRAC;
                    tap <= {ADDR_BITS{1'b0}};
                    acc <= 39'sd0;
                    if (scale == 2'd2) begin
                        state <= DONE;
                    end else begin
                        scale <= scale + 1'b1;
                    end
                end else begin
                    tap <= tap + 1'b1;
                end
            end
            //-----------------------------------------------------------------
            DONE: begin
                G_s1     <= g_result[0];
                G_s2     <= g_result[1];
                G_s3     <= g_result[2];
                DoG_fast <= g_result[0] - g_result[1];
                DoG_slow <= g_result[1] - g_result[2];
                result_valid <= 1'b1;
                state    <= IDLE;
            end
            endcase
        end
    end

endmodule
